#!/usr/bin/env bash
# scripts/orchestrator/handoff.sh <phase> [flags]
#
# Writes a structured hand-off document to the session workspace using
# the Lab 13 §B.2 schema (phase / inputs / outputs / open_questions /
# acceptance). Prints the absolute path of the generated doc on stdout
# so callers can pipe it into the next pane.
#
# Required arg:
#   <phase>   short slug, e.g. "6b" or "6b-dev"
#
# Flags (all repeatable where listed):
#   --role NAME           role of the writing agent (default: dev)
#   --out-dir DIR         directory to write into
#                          (default: $HANDOFF_OUT_DIR or .copilot/orchestrator-handoffs)
#   --input TEXT          repeatable; bullet under "## inputs"
#   --output TEXT         repeatable; bullet under "## outputs"
#   --question TEXT       repeatable; bullet under "## open_questions"
#   --accept TEXT         repeatable; bullet under "## acceptance"
#   --to-pane PANE        if set + tmux available, also send the path to PANE
#   --session NAME        tmux session to address with --to-pane
#
# Exit codes:
#   0  doc written; path on stdout
#   1  invalid usage (missing phase, bad flag)

set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "usage: $(basename "$0") <phase> [--role NAME] [--out-dir DIR] [--input TEXT]... [--output TEXT]... [--question TEXT]... [--accept TEXT]..." >&2
  exit 1
fi

PHASE="$1"; shift

case "$PHASE" in
  --*) echo "first arg must be a phase slug, not a flag: $PHASE" >&2; exit 1;;
esac

ROLE="dev"
OUT_DIR="${HANDOFF_OUT_DIR:-.copilot/orchestrator-handoffs}"
TO_PANE=""
SESSION="copilot-orch"

INPUTS=()
OUTPUTS=()
QUESTIONS=()
ACCEPT=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role)     ROLE="${2:?--role needs a value}"; shift 2;;
    --out-dir)  OUT_DIR="${2:?--out-dir needs a value}"; shift 2;;
    --input)    INPUTS+=("${2:?--input needs a value}"); shift 2;;
    --output)   OUTPUTS+=("${2:?--output needs a value}"); shift 2;;
    --question) QUESTIONS+=("${2:?--question needs a value}"); shift 2;;
    --accept)   ACCEPT+=("${2:?--accept needs a value}"); shift 2;;
    --to-pane)  TO_PANE="${2:?--to-pane needs a value}"; shift 2;;
    --session)  SESSION="${2:?--session needs a value}"; shift 2;;
    -h|--help)  sed -n '2,30p' "$0" >&2; exit 0;;
    *)          echo "unknown flag: $1" >&2; exit 1;;
  esac
done

mkdir -p "$OUT_DIR"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
SLUG="$(echo "$PHASE" | tr '[:upper:] /' '[:lower:]--' | tr -cd 'a-z0-9-')"
[[ -z "$SLUG" ]] && SLUG="phase"
DOC="${OUT_DIR%/}/${SLUG}-${TS}.md"

emit_bullets() {
  if [[ "$#" -eq 0 ]]; then
    echo "- _none_"
  else
    for item in "$@"; do
      printf -- "- %s\n" "$item"
    done
  fi
}

{
  cat <<EOF
---
phase: ${PHASE}
role: ${ROLE}
created_at: ${TS}
schema: lab13.B.2
---

# Hand-off — ${PHASE} (${ROLE})

## inputs
$(emit_bullets "${INPUTS[@]+"${INPUTS[@]}"}")

## outputs
$(emit_bullets "${OUTPUTS[@]+"${OUTPUTS[@]}"}")

## open_questions
$(emit_bullets "${QUESTIONS[@]+"${QUESTIONS[@]}"}")

## acceptance
$(emit_bullets "${ACCEPT[@]+"${ACCEPT[@]}"}")

---

_Generated by \`scripts/orchestrator/handoff.sh\`. Schema source:
[Lab 13 §B.2](../../labs/lab13.md) → operationalised in
[Lab 14](../../labs/lab14.md)._
EOF
} > "$DOC"

# Optional fan-out into the next tmux pane.
if [[ -n "$TO_PANE" ]] && command -v tmux >/dev/null 2>&1; then
  if tmux has-session -t "$SESSION" 2>/dev/null; then
    tmux send-keys -t "${SESSION}:work.${TO_PANE}" "cat ${DOC}" C-m || true
  fi
fi

echo "$DOC"
